use std::{fs, io::Write, os::unix::fs::OpenOptionsExt, path::Path};

fn quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Create new Finder-launchable shortcuts, never replacing existing files.
pub fn create(config: &Path, name: &str, directory: &Path) -> Result<(), String> {
    let binary = std::env::current_exe().map_err(|e| e.to_string())?;
    let config = config.canonicalize().map_err(|e| e.to_string())?;
    let binary = binary.to_str().ok_or("binary path must be UTF-8")?;
    let config = config.to_str().ok_or("config path must be UTF-8")?;
    fs::create_dir_all(directory).map_err(|e| e.to_string())?;
    let actions = [
        ("Connect", "connect"),
        ("Disconnect", "disconnect"),
        ("Status", "status"),
        ("Shell-VM", "shell"),
    ];
    let mut files = Vec::new();
    for (label, action) in actions {
        let path = directory.join(format!("{label}-{name}.command"));
        let file = fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .mode(0o700)
            .open(&path);
        match file {
            Ok(file) => files.push((path, file, action)),
            Err(e) => {
                for (path, _, _) in &files {
                    let _ = fs::remove_file(path);
                }
                return Err(format!("create shortcut {}: {e}", path.display()));
            }
        }
    }
    for (_, file, action) in &mut files {
        let workspace_option = if *action == "shell" {
            "--workspace="
        } else {
            "-- "
        };
        let script = format!(
            "#!/bin/bash\n# Generated by RWS. Commands run remotely only through exec/shell.\n{} --config {} {} {}{}\nresult=$?\nif [ \"$result\" -ne 0 ]; then printf '\\nRWS failed (exit %s). See the message above.\\n' \"$result\" >&2; fi\nif [ -t 0 ]; then printf '\\nPress Enter to close...'; read -r; fi\nexit \"$result\"\n",
            quote(binary),
            quote(config),
            action,
            workspace_option,
            quote(name)
        );
        if let Err(e) = file.write_all(script.as_bytes()) {
            for (path, _, _) in &files {
                let _ = fs::remove_file(path);
            }
            return Err(format!("write shortcuts: {e}"));
        }
    }
    Ok(())
}
